include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/generated_plugin_registrant.dart"
  errors:
    avoid_print: error
    invalid_assignment: error
    missing_return: error
    invalid_annotation_target: ignore

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_final_locals
    - unnecessary_this
    - annotate_overrides
    - camel_case_types
    - file_names
    - library_names
    - library_prefixes
    - avoid_print
    - always_declare_return_types
    - avoid_return_types_on_setters
    - avoid_shadowing_type_parameters
    - avoid_types_as_parameter_names
    - await_only_futures
    - empty_catches
    - empty_constructor_bodies
    - no_duplicate_case_values
    - null_closures
    - prefer_contains
    - prefer_is_empty
    - prefer_is_not_empty
    - recursive_getters
    - unawaited_futures
    - unrelated_type_equality_checks
    - valid_regexps
