name: about
description: "A new Flutter package project."
version: 0.0.1

publish_to: none

environment:
  sdk: ^3.10.7
  flutter: ">=1.17.0"

dependencies:
  core:
    path: ../core
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
