// Mocks generated by Mockito 5.4.6 from annotations
// in tv_series/test/test_helper/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:convert' as _i12;
import 'dart:typed_data' as _i13;

import 'package:core/core.dart' as _i6;
import 'package:dartz/dartz.dart' as _i2;
import 'package:flutter/src/widgets/navigator.dart' as _i11;
import 'package:flutter_bloc/flutter_bloc.dart' as _i14;
import 'package:http/http.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:sqflite/sqflite.dart' as _i10;
import 'package:tv_series/domain/entities/tv_series.dart' as _i7;
import 'package:tv_series/domain/entities/tv_series_detail.dart' as _i8;
import 'package:tv_series/tv_series.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTVSeriesDetailResponse_1 extends _i1.SmartFake
    implements _i3.TVSeriesDetailResponse {
  _FakeTVSeriesDetailResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTVSeriesRepository_2 extends _i1.SmartFake
    implements _i3.TVSeriesRepository {
  _FakeTVSeriesRepository_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_3 extends _i1.SmartFake implements _i4.Response {
  _FakeResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamedResponse_4 extends _i1.SmartFake
    implements _i4.StreamedResponse {
  _FakeStreamedResponse_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOnTheAirState_5 extends _i1.SmartFake implements _i3.OnTheAirState {
  _FakeOnTheAirState_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePopularTVSeriesState_6 extends _i1.SmartFake
    implements _i3.PopularTVSeriesState {
  _FakePopularTVSeriesState_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTopRatedTVSeriesState_7 extends _i1.SmartFake
    implements _i3.TopRatedTVSeriesState {
  _FakeTopRatedTVSeriesState_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTVSeriesDetailState_8 extends _i1.SmartFake
    implements _i3.TVSeriesDetailState {
  _FakeTVSeriesDetailState_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTVSeriesRecommendationsState_9 extends _i1.SmartFake
    implements _i3.TVSeriesRecommendationsState {
  _FakeTVSeriesRecommendationsState_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeGetWatchListStatusTVSeries_10 extends _i1.SmartFake
    implements _i3.GetWatchListStatusTVSeries {
  _FakeGetWatchListStatusTVSeries_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSaveWatchlistTVSeries_11 extends _i1.SmartFake
    implements _i3.SaveWatchlistTVSeries {
  _FakeSaveWatchlistTVSeries_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRemoveWatchlistTVSeries_12 extends _i1.SmartFake
    implements _i3.RemoveWatchlistTVSeries {
  _FakeRemoveWatchlistTVSeries_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWatchlistTVSeriesStatusState_13 extends _i1.SmartFake
    implements _i3.WatchlistTVSeriesStatusState {
  _FakeWatchlistTVSeriesStatusState_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeWatchlistTVSeriesState_14 extends _i1.SmartFake
    implements _i3.WatchlistTVSeriesState {
  _FakeWatchlistTVSeriesState_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSearchTVSeriesState_15 extends _i1.SmartFake
    implements _i3.SearchTVSeriesState {
  _FakeSearchTVSeriesState_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TVSeriesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTVSeriesRepository extends _i1.Mock
    implements _i3.TVSeriesRepository {
  MockTVSeriesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.TVSeries>>>
  getOnTheAirTVSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getOnTheAirTVSeries, []),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, List<_i7.TVSeries>>>.value(
                  _FakeEither_0<_i6.Failure, List<_i7.TVSeries>>(
                    this,
                    Invocation.method(#getOnTheAirTVSeries, []),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, List<_i7.TVSeries>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.TVSeries>>>
  getPopularTVSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getPopularTVSeries, []),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, List<_i7.TVSeries>>>.value(
                  _FakeEither_0<_i6.Failure, List<_i7.TVSeries>>(
                    this,
                    Invocation.method(#getPopularTVSeries, []),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, List<_i7.TVSeries>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.TVSeries>>>
  getTopRatedTVSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getTopRatedTVSeries, []),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, List<_i7.TVSeries>>>.value(
                  _FakeEither_0<_i6.Failure, List<_i7.TVSeries>>(
                    this,
                    Invocation.method(#getTopRatedTVSeries, []),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, List<_i7.TVSeries>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i8.TVSeriesDetail>> getTVSeriesDetail(
    int? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTVSeriesDetail, [id]),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, _i8.TVSeriesDetail>>.value(
                  _FakeEither_0<_i6.Failure, _i8.TVSeriesDetail>(
                    this,
                    Invocation.method(#getTVSeriesDetail, [id]),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, _i8.TVSeriesDetail>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.TVSeries>>>
  getTVSeriesRecommendations(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTVSeriesRecommendations, [id]),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, List<_i7.TVSeries>>>.value(
                  _FakeEither_0<_i6.Failure, List<_i7.TVSeries>>(
                    this,
                    Invocation.method(#getTVSeriesRecommendations, [id]),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, List<_i7.TVSeries>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.TVSeries>>> searchTVSeries(
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchTVSeries, [query]),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, List<_i7.TVSeries>>>.value(
                  _FakeEither_0<_i6.Failure, List<_i7.TVSeries>>(
                    this,
                    Invocation.method(#searchTVSeries, [query]),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, List<_i7.TVSeries>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, String>> saveWatchlist(
    _i8.TVSeriesDetail? tvSeries,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveWatchlist, [tvSeries]),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, String>>.value(
              _FakeEither_0<_i6.Failure, String>(
                this,
                Invocation.method(#saveWatchlist, [tvSeries]),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, String>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, String>> removeWatchlist(
    _i8.TVSeriesDetail? tvSeries,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeWatchlist, [tvSeries]),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, String>>.value(
              _FakeEither_0<_i6.Failure, String>(
                this,
                Invocation.method(#removeWatchlist, [tvSeries]),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, String>>);

  @override
  _i5.Future<bool> isAddedToWatchlist(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#isAddedToWatchlist, [id]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.TVSeries>>>
  getWatchlistTVSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistTVSeries, []),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, List<_i7.TVSeries>>>.value(
                  _FakeEither_0<_i6.Failure, List<_i7.TVSeries>>(
                    this,
                    Invocation.method(#getWatchlistTVSeries, []),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, List<_i7.TVSeries>>>);
}

/// A class which mocks [TVSeriesRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTVSeriesRemoteDataSource extends _i1.Mock
    implements _i3.TVSeriesRemoteDataSource {
  MockTVSeriesRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i3.TVSeriesModel>> getOnTheAirTVSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getOnTheAirTVSeries, []),
            returnValue: _i5.Future<List<_i3.TVSeriesModel>>.value(
              <_i3.TVSeriesModel>[],
            ),
          )
          as _i5.Future<List<_i3.TVSeriesModel>>);

  @override
  _i5.Future<List<_i3.TVSeriesModel>> getPopularTVSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getPopularTVSeries, []),
            returnValue: _i5.Future<List<_i3.TVSeriesModel>>.value(
              <_i3.TVSeriesModel>[],
            ),
          )
          as _i5.Future<List<_i3.TVSeriesModel>>);

  @override
  _i5.Future<List<_i3.TVSeriesModel>> getTopRatedTVSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getTopRatedTVSeries, []),
            returnValue: _i5.Future<List<_i3.TVSeriesModel>>.value(
              <_i3.TVSeriesModel>[],
            ),
          )
          as _i5.Future<List<_i3.TVSeriesModel>>);

  @override
  _i5.Future<_i3.TVSeriesDetailResponse> getTVSeriesDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTVSeriesDetail, [id]),
            returnValue: _i5.Future<_i3.TVSeriesDetailResponse>.value(
              _FakeTVSeriesDetailResponse_1(
                this,
                Invocation.method(#getTVSeriesDetail, [id]),
              ),
            ),
          )
          as _i5.Future<_i3.TVSeriesDetailResponse>);

  @override
  _i5.Future<List<_i3.TVSeriesModel>> getTVSeriesRecommendations(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTVSeriesRecommendations, [id]),
            returnValue: _i5.Future<List<_i3.TVSeriesModel>>.value(
              <_i3.TVSeriesModel>[],
            ),
          )
          as _i5.Future<List<_i3.TVSeriesModel>>);

  @override
  _i5.Future<List<_i3.TVSeriesModel>> searchTVSeries(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchTVSeries, [query]),
            returnValue: _i5.Future<List<_i3.TVSeriesModel>>.value(
              <_i3.TVSeriesModel>[],
            ),
          )
          as _i5.Future<List<_i3.TVSeriesModel>>);
}

/// A class which mocks [TVSeriesLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTVSeriesLocalDataSource extends _i1.Mock
    implements _i3.TVSeriesLocalDataSource {
  MockTVSeriesLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<String> insertWatchlist(_i3.TVSeriesTable? tvSeries) =>
      (super.noSuchMethod(
            Invocation.method(#insertWatchlist, [tvSeries]),
            returnValue: _i5.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#insertWatchlist, [tvSeries]),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<String> removeWatchlist(_i3.TVSeriesTable? tvSeries) =>
      (super.noSuchMethod(
            Invocation.method(#removeWatchlist, [tvSeries]),
            returnValue: _i5.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#removeWatchlist, [tvSeries]),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<_i3.TVSeriesTable?> getTVSeriesById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTVSeriesById, [id]),
            returnValue: _i5.Future<_i3.TVSeriesTable?>.value(),
          )
          as _i5.Future<_i3.TVSeriesTable?>);

  @override
  _i5.Future<List<_i3.TVSeriesTable>> getWatchlistTVSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistTVSeries, []),
            returnValue: _i5.Future<List<_i3.TVSeriesTable>>.value(
              <_i3.TVSeriesTable>[],
            ),
          )
          as _i5.Future<List<_i3.TVSeriesTable>>);
}

/// A class which mocks [TVSeriesDatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockTVSeriesDatabaseHelper extends _i1.Mock
    implements _i3.TVSeriesDatabaseHelper {
  MockTVSeriesDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i10.Database?> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i5.Future<_i10.Database?>.value(),
          )
          as _i5.Future<_i10.Database?>);

  @override
  _i5.Future<int> insertWatchlistTVSeries(_i3.TVSeriesTable? tvSeries) =>
      (super.noSuchMethod(
            Invocation.method(#insertWatchlistTVSeries, [tvSeries]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> removeWatchlistTVSeries(_i3.TVSeriesTable? tvSeries) =>
      (super.noSuchMethod(
            Invocation.method(#removeWatchlistTVSeries, [tvSeries]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<Map<String, dynamic>?> getTVSeriesById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTVSeriesById, [id]),
            returnValue: _i5.Future<Map<String, dynamic>?>.value(),
          )
          as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getWatchlistTVSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistTVSeries, []),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [GetOnTheAirTVSeries].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetOnTheAirTVSeries extends _i1.Mock
    implements _i3.GetOnTheAirTVSeries {
  MockGetOnTheAirTVSeries() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.TVSeriesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTVSeriesRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.TVSeriesRepository);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.TVSeries>>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, List<_i7.TVSeries>>>.value(
                  _FakeEither_0<_i6.Failure, List<_i7.TVSeries>>(
                    this,
                    Invocation.method(#execute, []),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, List<_i7.TVSeries>>>);
}

/// A class which mocks [GetPopularTVSeries].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPopularTVSeries extends _i1.Mock
    implements _i3.GetPopularTVSeries {
  MockGetPopularTVSeries() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.TVSeriesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTVSeriesRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.TVSeriesRepository);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.TVSeries>>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, List<_i7.TVSeries>>>.value(
                  _FakeEither_0<_i6.Failure, List<_i7.TVSeries>>(
                    this,
                    Invocation.method(#execute, []),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, List<_i7.TVSeries>>>);
}

/// A class which mocks [GetTVSeriesDetail].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTVSeriesDetail extends _i1.Mock implements _i3.GetTVSeriesDetail {
  MockGetTVSeriesDetail() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.TVSeriesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTVSeriesRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.TVSeriesRepository);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i8.TVSeriesDetail>> execute(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [id]),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, _i8.TVSeriesDetail>>.value(
                  _FakeEither_0<_i6.Failure, _i8.TVSeriesDetail>(
                    this,
                    Invocation.method(#execute, [id]),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, _i8.TVSeriesDetail>>);
}

/// A class which mocks [GetTVSeriesRecommendations].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTVSeriesRecommendations extends _i1.Mock
    implements _i3.GetTVSeriesRecommendations {
  MockGetTVSeriesRecommendations() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.TVSeriesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTVSeriesRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.TVSeriesRepository);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.TVSeries>>> execute(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [id]),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, List<_i7.TVSeries>>>.value(
                  _FakeEither_0<_i6.Failure, List<_i7.TVSeries>>(
                    this,
                    Invocation.method(#execute, [id]),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, List<_i7.TVSeries>>>);
}

/// A class which mocks [GetTopRatedTVSeries].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTopRatedTVSeries extends _i1.Mock
    implements _i3.GetTopRatedTVSeries {
  MockGetTopRatedTVSeries() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.TVSeriesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTVSeriesRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.TVSeriesRepository);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.TVSeries>>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, List<_i7.TVSeries>>>.value(
                  _FakeEither_0<_i6.Failure, List<_i7.TVSeries>>(
                    this,
                    Invocation.method(#execute, []),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, List<_i7.TVSeries>>>);
}

/// A class which mocks [GetWatchListStatusTVSeries].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchListStatusTVSeries extends _i1.Mock
    implements _i3.GetWatchListStatusTVSeries {
  MockGetWatchListStatusTVSeries() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.TVSeriesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTVSeriesRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.TVSeriesRepository);

  @override
  _i5.Future<bool> execute(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [id]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}

/// A class which mocks [GetWatchlistTVSeries].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchlistTVSeries extends _i1.Mock
    implements _i3.GetWatchlistTVSeries {
  MockGetWatchlistTVSeries() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.TVSeries>>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, List<_i7.TVSeries>>>.value(
                  _FakeEither_0<_i6.Failure, List<_i7.TVSeries>>(
                    this,
                    Invocation.method(#execute, []),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, List<_i7.TVSeries>>>);
}

/// A class which mocks [SaveWatchlistTVSeries].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveWatchlistTVSeries extends _i1.Mock
    implements _i3.SaveWatchlistTVSeries {
  MockSaveWatchlistTVSeries() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.TVSeriesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTVSeriesRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.TVSeriesRepository);

  @override
  _i5.Future<_i2.Either<_i6.Failure, String>> execute(
    _i8.TVSeriesDetail? tvSeries,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [tvSeries]),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, String>>.value(
              _FakeEither_0<_i6.Failure, String>(
                this,
                Invocation.method(#execute, [tvSeries]),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, String>>);
}

/// A class which mocks [RemoveWatchlistTVSeries].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveWatchlistTVSeries extends _i1.Mock
    implements _i3.RemoveWatchlistTVSeries {
  MockRemoveWatchlistTVSeries() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.TVSeriesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTVSeriesRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.TVSeriesRepository);

  @override
  _i5.Future<_i2.Either<_i6.Failure, String>> execute(
    _i8.TVSeriesDetail? tvSeries,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [tvSeries]),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, String>>.value(
              _FakeEither_0<_i6.Failure, String>(
                this,
                Invocation.method(#execute, [tvSeries]),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, String>>);
}

/// A class which mocks [SearchTVSeries].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchTVSeries extends _i1.Mock implements _i3.SearchTVSeries {
  MockSearchTVSeries() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.TVSeriesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTVSeriesRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.TVSeriesRepository);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.TVSeries>>> execute(
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [query]),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, List<_i7.TVSeries>>>.value(
                  _FakeEither_0<_i6.Failure, List<_i7.TVSeries>>(
                    this,
                    Invocation.method(#execute, [query]),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, List<_i7.TVSeries>>>);
}

/// A class which mocks [NavigatorObserver].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigatorObserver extends _i1.Mock implements _i11.NavigatorObserver {
  MockNavigatorObserver() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void didPush(
    _i11.Route<dynamic>? route,
    _i11.Route<dynamic>? previousRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didPush, [route, previousRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didPop(_i11.Route<dynamic>? route, _i11.Route<dynamic>? previousRoute) =>
      super.noSuchMethod(
        Invocation.method(#didPop, [route, previousRoute]),
        returnValueForMissingStub: null,
      );

  @override
  void didRemove(
    _i11.Route<dynamic>? route,
    _i11.Route<dynamic>? previousRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didRemove, [route, previousRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didReplace({
    _i11.Route<dynamic>? newRoute,
    _i11.Route<dynamic>? oldRoute,
  }) => super.noSuchMethod(
    Invocation.method(#didReplace, [], {
      #newRoute: newRoute,
      #oldRoute: oldRoute,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeTop(
    _i11.Route<dynamic>? topRoute,
    _i11.Route<dynamic>? previousTopRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didChangeTop, [topRoute, previousTopRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didStartUserGesture(
    _i11.Route<dynamic>? route,
    _i11.Route<dynamic>? previousRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didStartUserGesture, [route, previousRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didStopUserGesture() => super.noSuchMethod(
    Invocation.method(#didStopUserGesture, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i4.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i4.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#head, [url], {#headers: headers}),
            returnValue: _i5.Future<_i4.Response>.value(
              _FakeResponse_3(
                this,
                Invocation.method(#head, [url], {#headers: headers}),
              ),
            ),
          )
          as _i5.Future<_i4.Response>);

  @override
  _i5.Future<_i4.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#get, [url], {#headers: headers}),
            returnValue: _i5.Future<_i4.Response>.value(
              _FakeResponse_3(
                this,
                Invocation.method(#get, [url], {#headers: headers}),
              ),
            ),
          )
          as _i5.Future<_i4.Response>);

  @override
  _i5.Future<_i4.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i12.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i5.Future<_i4.Response>.value(
              _FakeResponse_3(
                this,
                Invocation.method(
                  #post,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i5.Future<_i4.Response>);

  @override
  _i5.Future<_i4.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i12.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i5.Future<_i4.Response>.value(
              _FakeResponse_3(
                this,
                Invocation.method(
                  #put,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i5.Future<_i4.Response>);

  @override
  _i5.Future<_i4.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i12.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i5.Future<_i4.Response>.value(
              _FakeResponse_3(
                this,
                Invocation.method(
                  #patch,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i5.Future<_i4.Response>);

  @override
  _i5.Future<_i4.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i12.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i5.Future<_i4.Response>.value(
              _FakeResponse_3(
                this,
                Invocation.method(
                  #delete,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i5.Future<_i4.Response>);

  @override
  _i5.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#read, [url], {#headers: headers}),
            returnValue: _i5.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#read, [url], {#headers: headers}),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<_i13.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readBytes, [url], {#headers: headers}),
            returnValue: _i5.Future<_i13.Uint8List>.value(_i13.Uint8List(0)),
          )
          as _i5.Future<_i13.Uint8List>);

  @override
  _i5.Future<_i4.StreamedResponse> send(_i4.BaseRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#send, [request]),
            returnValue: _i5.Future<_i4.StreamedResponse>.value(
              _FakeStreamedResponse_4(
                this,
                Invocation.method(#send, [request]),
              ),
            ),
          )
          as _i5.Future<_i4.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
    Invocation.method(#close, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [OnTheAirCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockOnTheAirCubit extends _i1.Mock implements _i3.OnTheAirCubit {
  MockOnTheAirCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.OnTheAirState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeOnTheAirState_5(this, Invocation.getter(#state)),
          )
          as _i3.OnTheAirState);

  @override
  _i5.Stream<_i3.OnTheAirState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i5.Stream<_i3.OnTheAirState>.empty(),
          )
          as _i5.Stream<_i3.OnTheAirState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i5.Future<void> fetchOnTheAirTVSeries() =>
      (super.noSuchMethod(
            Invocation.method(#fetchOnTheAirTVSeries, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void emit(_i3.OnTheAirState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i14.Change<_i3.OnTheAirState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [PopularTVSeriesCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockPopularTVSeriesCubit extends _i1.Mock
    implements _i3.PopularTVSeriesCubit {
  MockPopularTVSeriesCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.PopularTVSeriesState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakePopularTVSeriesState_6(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i3.PopularTVSeriesState);

  @override
  _i5.Stream<_i3.PopularTVSeriesState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i5.Stream<_i3.PopularTVSeriesState>.empty(),
          )
          as _i5.Stream<_i3.PopularTVSeriesState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i5.Future<void> fetchPopularTVSeries() =>
      (super.noSuchMethod(
            Invocation.method(#fetchPopularTVSeries, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void emit(_i3.PopularTVSeriesState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i14.Change<_i3.PopularTVSeriesState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [TopRatedTVSeriesCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockTopRatedTVSeriesCubit extends _i1.Mock
    implements _i3.TopRatedTVSeriesCubit {
  MockTopRatedTVSeriesCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.TopRatedTVSeriesState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeTopRatedTVSeriesState_7(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i3.TopRatedTVSeriesState);

  @override
  _i5.Stream<_i3.TopRatedTVSeriesState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i5.Stream<_i3.TopRatedTVSeriesState>.empty(),
          )
          as _i5.Stream<_i3.TopRatedTVSeriesState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i5.Future<void> fetchTopRatedTVSeries() =>
      (super.noSuchMethod(
            Invocation.method(#fetchTopRatedTVSeries, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void emit(_i3.TopRatedTVSeriesState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i14.Change<_i3.TopRatedTVSeriesState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [TVSeriesDetailCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockTVSeriesDetailCubit extends _i1.Mock
    implements _i3.TVSeriesDetailCubit {
  MockTVSeriesDetailCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.TVSeriesDetailState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeTVSeriesDetailState_8(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i3.TVSeriesDetailState);

  @override
  _i5.Stream<_i3.TVSeriesDetailState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i5.Stream<_i3.TVSeriesDetailState>.empty(),
          )
          as _i5.Stream<_i3.TVSeriesDetailState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i5.Future<void> fetchTVSeriesDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchTVSeriesDetail, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void emit(_i3.TVSeriesDetailState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i14.Change<_i3.TVSeriesDetailState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [TVSeriesRecommendationsCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockTVSeriesRecommendationsCubit extends _i1.Mock
    implements _i3.TVSeriesRecommendationsCubit {
  MockTVSeriesRecommendationsCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.TVSeriesRecommendationsState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeTVSeriesRecommendationsState_9(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i3.TVSeriesRecommendationsState);

  @override
  _i5.Stream<_i3.TVSeriesRecommendationsState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i5.Stream<_i3.TVSeriesRecommendationsState>.empty(),
          )
          as _i5.Stream<_i3.TVSeriesRecommendationsState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i5.Future<void> fetchTVSeriesRecommendations(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchTVSeriesRecommendations, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void emit(_i3.TVSeriesRecommendationsState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i14.Change<_i3.TVSeriesRecommendationsState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [WatchlistTVSeriesStatusCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchlistTVSeriesStatusCubit extends _i1.Mock
    implements _i3.WatchlistTVSeriesStatusCubit {
  MockWatchlistTVSeriesStatusCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.GetWatchListStatusTVSeries get getWatchListStatusTVSeries =>
      (super.noSuchMethod(
            Invocation.getter(#getWatchListStatusTVSeries),
            returnValue: _FakeGetWatchListStatusTVSeries_10(
              this,
              Invocation.getter(#getWatchListStatusTVSeries),
            ),
          )
          as _i3.GetWatchListStatusTVSeries);

  @override
  _i3.SaveWatchlistTVSeries get saveWatchlistTVSeries =>
      (super.noSuchMethod(
            Invocation.getter(#saveWatchlistTVSeries),
            returnValue: _FakeSaveWatchlistTVSeries_11(
              this,
              Invocation.getter(#saveWatchlistTVSeries),
            ),
          )
          as _i3.SaveWatchlistTVSeries);

  @override
  _i3.RemoveWatchlistTVSeries get removeWatchlistTVSeries =>
      (super.noSuchMethod(
            Invocation.getter(#removeWatchlistTVSeries),
            returnValue: _FakeRemoveWatchlistTVSeries_12(
              this,
              Invocation.getter(#removeWatchlistTVSeries),
            ),
          )
          as _i3.RemoveWatchlistTVSeries);

  @override
  _i3.WatchlistTVSeriesStatusState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeWatchlistTVSeriesStatusState_13(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i3.WatchlistTVSeriesStatusState);

  @override
  _i5.Stream<_i3.WatchlistTVSeriesStatusState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i5.Stream<_i3.WatchlistTVSeriesStatusState>.empty(),
          )
          as _i5.Stream<_i3.WatchlistTVSeriesStatusState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void loadWatchlistStatus(int? id) => super.noSuchMethod(
    Invocation.method(#loadWatchlistStatus, [id]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> addWatchlist(_i8.TVSeriesDetail? tvSeries) =>
      (super.noSuchMethod(
            Invocation.method(#addWatchlist, [tvSeries]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> removeFromWatchlist(_i8.TVSeriesDetail? tvSeries) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromWatchlist, [tvSeries]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void emit(_i3.WatchlistTVSeriesStatusState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i14.Change<_i3.WatchlistTVSeriesStatusState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [WatchlistTVSeriesCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchlistTVSeriesCubit extends _i1.Mock
    implements _i3.WatchlistTVSeriesCubit {
  MockWatchlistTVSeriesCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.WatchlistTVSeriesState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeWatchlistTVSeriesState_14(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i3.WatchlistTVSeriesState);

  @override
  _i5.Stream<_i3.WatchlistTVSeriesState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i5.Stream<_i3.WatchlistTVSeriesState>.empty(),
          )
          as _i5.Stream<_i3.WatchlistTVSeriesState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i5.Future<void> fetchWatchlistTVSeries() =>
      (super.noSuchMethod(
            Invocation.method(#fetchWatchlistTVSeries, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void emit(_i3.WatchlistTVSeriesState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i14.Change<_i3.WatchlistTVSeriesState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [SearchTVSeriesCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchTVSeriesCubit extends _i1.Mock
    implements _i3.SearchTVSeriesCubit {
  MockSearchTVSeriesCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.SearchTVSeriesState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeSearchTVSeriesState_15(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i3.SearchTVSeriesState);

  @override
  _i5.Stream<_i3.SearchTVSeriesState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i5.Stream<_i3.SearchTVSeriesState>.empty(),
          )
          as _i5.Stream<_i3.SearchTVSeriesState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i5.Future<void> onQueryChanged(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#onQueryChanged, [query]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void emit(_i3.SearchTVSeriesState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i14.Change<_i3.SearchTVSeriesState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
