// Mocks generated by Mockito 5.4.6 from annotations
// in tv_series/test/test_helper/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:convert' as _i11;
import 'dart:typed_data' as _i12;

import 'package:core/core.dart' as _i6;
import 'package:dartz/dartz.dart' as _i2;
import 'package:http/http.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:sqflite/sqflite.dart' as _i10;
import 'package:tv_series/domain/entities/tv_series.dart' as _i7;
import 'package:tv_series/domain/entities/tv_series_detail.dart' as _i8;
import 'package:tv_series/tv_series.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTVSeriesDetailResponse_1 extends _i1.SmartFake
    implements _i3.TVSeriesDetailResponse {
  _FakeTVSeriesDetailResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_2 extends _i1.SmartFake implements _i4.Response {
  _FakeResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamedResponse_3 extends _i1.SmartFake
    implements _i4.StreamedResponse {
  _FakeStreamedResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TVSeriesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTVSeriesRepository extends _i1.Mock
    implements _i3.TVSeriesRepository {
  MockTVSeriesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.TVSeries>>>
  getOnTheAirTVSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getOnTheAirTVSeries, []),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, List<_i7.TVSeries>>>.value(
                  _FakeEither_0<_i6.Failure, List<_i7.TVSeries>>(
                    this,
                    Invocation.method(#getOnTheAirTVSeries, []),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, List<_i7.TVSeries>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.TVSeries>>>
  getPopularTVSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getPopularTVSeries, []),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, List<_i7.TVSeries>>>.value(
                  _FakeEither_0<_i6.Failure, List<_i7.TVSeries>>(
                    this,
                    Invocation.method(#getPopularTVSeries, []),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, List<_i7.TVSeries>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.TVSeries>>>
  getTopRatedTVSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getTopRatedTVSeries, []),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, List<_i7.TVSeries>>>.value(
                  _FakeEither_0<_i6.Failure, List<_i7.TVSeries>>(
                    this,
                    Invocation.method(#getTopRatedTVSeries, []),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, List<_i7.TVSeries>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i8.TVSeriesDetail>> getTVSeriesDetail(
    int? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTVSeriesDetail, [id]),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, _i8.TVSeriesDetail>>.value(
                  _FakeEither_0<_i6.Failure, _i8.TVSeriesDetail>(
                    this,
                    Invocation.method(#getTVSeriesDetail, [id]),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, _i8.TVSeriesDetail>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.TVSeries>>>
  getTVSeriesRecommendations(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTVSeriesRecommendations, [id]),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, List<_i7.TVSeries>>>.value(
                  _FakeEither_0<_i6.Failure, List<_i7.TVSeries>>(
                    this,
                    Invocation.method(#getTVSeriesRecommendations, [id]),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, List<_i7.TVSeries>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.TVSeries>>> searchTVSeries(
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchTVSeries, [query]),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, List<_i7.TVSeries>>>.value(
                  _FakeEither_0<_i6.Failure, List<_i7.TVSeries>>(
                    this,
                    Invocation.method(#searchTVSeries, [query]),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, List<_i7.TVSeries>>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, String>> saveWatchlist(
    _i8.TVSeriesDetail? tvSeries,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveWatchlist, [tvSeries]),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, String>>.value(
              _FakeEither_0<_i6.Failure, String>(
                this,
                Invocation.method(#saveWatchlist, [tvSeries]),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, String>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, String>> removeWatchlist(
    _i8.TVSeriesDetail? tvSeries,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeWatchlist, [tvSeries]),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, String>>.value(
              _FakeEither_0<_i6.Failure, String>(
                this,
                Invocation.method(#removeWatchlist, [tvSeries]),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, String>>);

  @override
  _i5.Future<bool> isAddedToWatchlist(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#isAddedToWatchlist, [id]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.TVSeries>>>
  getWatchlistTVSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistTVSeries, []),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, List<_i7.TVSeries>>>.value(
                  _FakeEither_0<_i6.Failure, List<_i7.TVSeries>>(
                    this,
                    Invocation.method(#getWatchlistTVSeries, []),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, List<_i7.TVSeries>>>);
}

/// A class which mocks [TVSeriesRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTVSeriesRemoteDataSource extends _i1.Mock
    implements _i3.TVSeriesRemoteDataSource {
  MockTVSeriesRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i3.TVSeriesModel>> getOnTheAirTVSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getOnTheAirTVSeries, []),
            returnValue: _i5.Future<List<_i3.TVSeriesModel>>.value(
              <_i3.TVSeriesModel>[],
            ),
          )
          as _i5.Future<List<_i3.TVSeriesModel>>);

  @override
  _i5.Future<List<_i3.TVSeriesModel>> getPopularTVSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getPopularTVSeries, []),
            returnValue: _i5.Future<List<_i3.TVSeriesModel>>.value(
              <_i3.TVSeriesModel>[],
            ),
          )
          as _i5.Future<List<_i3.TVSeriesModel>>);

  @override
  _i5.Future<List<_i3.TVSeriesModel>> getTopRatedTVSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getTopRatedTVSeries, []),
            returnValue: _i5.Future<List<_i3.TVSeriesModel>>.value(
              <_i3.TVSeriesModel>[],
            ),
          )
          as _i5.Future<List<_i3.TVSeriesModel>>);

  @override
  _i5.Future<_i3.TVSeriesDetailResponse> getTVSeriesDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTVSeriesDetail, [id]),
            returnValue: _i5.Future<_i3.TVSeriesDetailResponse>.value(
              _FakeTVSeriesDetailResponse_1(
                this,
                Invocation.method(#getTVSeriesDetail, [id]),
              ),
            ),
          )
          as _i5.Future<_i3.TVSeriesDetailResponse>);

  @override
  _i5.Future<List<_i3.TVSeriesModel>> getTVSeriesRecommendations(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTVSeriesRecommendations, [id]),
            returnValue: _i5.Future<List<_i3.TVSeriesModel>>.value(
              <_i3.TVSeriesModel>[],
            ),
          )
          as _i5.Future<List<_i3.TVSeriesModel>>);

  @override
  _i5.Future<List<_i3.TVSeriesModel>> searchTVSeries(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchTVSeries, [query]),
            returnValue: _i5.Future<List<_i3.TVSeriesModel>>.value(
              <_i3.TVSeriesModel>[],
            ),
          )
          as _i5.Future<List<_i3.TVSeriesModel>>);
}

/// A class which mocks [TVSeriesLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTVSeriesLocalDataSource extends _i1.Mock
    implements _i3.TVSeriesLocalDataSource {
  MockTVSeriesLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<String> insertWatchlist(_i3.TVSeriesTable? tvSeries) =>
      (super.noSuchMethod(
            Invocation.method(#insertWatchlist, [tvSeries]),
            returnValue: _i5.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#insertWatchlist, [tvSeries]),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<String> removeWatchlist(_i3.TVSeriesTable? tvSeries) =>
      (super.noSuchMethod(
            Invocation.method(#removeWatchlist, [tvSeries]),
            returnValue: _i5.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#removeWatchlist, [tvSeries]),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<_i3.TVSeriesTable?> getTVSeriesById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTVSeriesById, [id]),
            returnValue: _i5.Future<_i3.TVSeriesTable?>.value(),
          )
          as _i5.Future<_i3.TVSeriesTable?>);

  @override
  _i5.Future<List<_i3.TVSeriesTable>> getWatchlistTVSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistTVSeries, []),
            returnValue: _i5.Future<List<_i3.TVSeriesTable>>.value(
              <_i3.TVSeriesTable>[],
            ),
          )
          as _i5.Future<List<_i3.TVSeriesTable>>);
}

/// A class which mocks [TVSeriesDatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockTVSeriesDatabaseHelper extends _i1.Mock
    implements _i3.TVSeriesDatabaseHelper {
  MockTVSeriesDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i10.Database?> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i5.Future<_i10.Database?>.value(),
          )
          as _i5.Future<_i10.Database?>);

  @override
  _i5.Future<int> insertWatchlistTVSeries(_i3.TVSeriesTable? tvSeries) =>
      (super.noSuchMethod(
            Invocation.method(#insertWatchlistTVSeries, [tvSeries]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> removeWatchlistTVSeries(_i3.TVSeriesTable? tvSeries) =>
      (super.noSuchMethod(
            Invocation.method(#removeWatchlistTVSeries, [tvSeries]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<Map<String, dynamic>?> getTVSeriesById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTVSeriesById, [id]),
            returnValue: _i5.Future<Map<String, dynamic>?>.value(),
          )
          as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getWatchlistTVSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistTVSeries, []),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i4.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i4.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#head, [url], {#headers: headers}),
            returnValue: _i5.Future<_i4.Response>.value(
              _FakeResponse_2(
                this,
                Invocation.method(#head, [url], {#headers: headers}),
              ),
            ),
          )
          as _i5.Future<_i4.Response>);

  @override
  _i5.Future<_i4.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#get, [url], {#headers: headers}),
            returnValue: _i5.Future<_i4.Response>.value(
              _FakeResponse_2(
                this,
                Invocation.method(#get, [url], {#headers: headers}),
              ),
            ),
          )
          as _i5.Future<_i4.Response>);

  @override
  _i5.Future<_i4.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i11.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i5.Future<_i4.Response>.value(
              _FakeResponse_2(
                this,
                Invocation.method(
                  #post,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i5.Future<_i4.Response>);

  @override
  _i5.Future<_i4.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i11.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i5.Future<_i4.Response>.value(
              _FakeResponse_2(
                this,
                Invocation.method(
                  #put,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i5.Future<_i4.Response>);

  @override
  _i5.Future<_i4.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i11.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i5.Future<_i4.Response>.value(
              _FakeResponse_2(
                this,
                Invocation.method(
                  #patch,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i5.Future<_i4.Response>);

  @override
  _i5.Future<_i4.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i11.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i5.Future<_i4.Response>.value(
              _FakeResponse_2(
                this,
                Invocation.method(
                  #delete,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i5.Future<_i4.Response>);

  @override
  _i5.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#read, [url], {#headers: headers}),
            returnValue: _i5.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#read, [url], {#headers: headers}),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<_i12.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readBytes, [url], {#headers: headers}),
            returnValue: _i5.Future<_i12.Uint8List>.value(_i12.Uint8List(0)),
          )
          as _i5.Future<_i12.Uint8List>);

  @override
  _i5.Future<_i4.StreamedResponse> send(_i4.BaseRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#send, [request]),
            returnValue: _i5.Future<_i4.StreamedResponse>.value(
              _FakeStreamedResponse_3(
                this,
                Invocation.method(#send, [request]),
              ),
            ),
          )
          as _i5.Future<_i4.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
    Invocation.method(#close, []),
    returnValueForMissingStub: null,
  );
}
